### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by nt4f04uNd** [adolfos94/Bareiss-Algorithm#1]
When I provide matrix `[[ 1, 100, 20 ],[ 20, 10, 57 ],[ -2, -3, 100 ]]` it gives `NaN` as the output.
Initially, I have found this problem when I was implementing algorithm in c++ (like [here](https://cs.nyu.edu/exact/core/download/core_v1.4/core_v1.4/progs/bareiss/bareiss.cpp)) and came on your implementation. Is this a problem of algorithm or it's the issue of implementations?

**Comment by adolfos94** [comment]
I think it is related with the implementations, seems to be an edge case. I do not have time to fix it, but if you find a solution lemme know, so I can patch it.

**Comment by nt4f04uNd** [comment]
This solution to this [here](https://www.math.usm.edu/perry/Research/Thesis_DRL.pdf), but the fix kinda eliminates all the benefits of this algorithm and by the way this solution is not full, as in it they just swap 1 row, but what if after swap the 0 is still on its place? In this case we have to find any element in column that is non zero and swap that row instead. So I would prefer LU decomposition instead of it

**Comment by nt4f04uNd** [comment]
Type "Division by Zero in Bareiss" to find needed material in this document

**Comment by adolfos94** [comment]
I implemented something similar using the Gauss-Jacques method to calculate the modular inverse of a matrix. I validated if the pivot is zero just swap the rows.

Take a look at the function isPivotZero.

https://github.com/adolfos94/Gauss-Jacques/blob/master/index.js

If you want to create a workaround in this code, feel free to do it.
